basePath: /v1
host: petstore.swagger.io
info:
  contact:
    email: solid.utkin@gmail.com
    name: API Support
    url: http://www.swagger.io/support
  description: API of dividend calendar.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Dividend Calendar API
  version: "1.0"
paths: {}
swagger: "2.0"
